services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./rust-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
